
package test.db;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;


public class Loginn extends javax.swing.JFrame {

    MySQLConnect ms = new MySQLConnect();
     public int mod;
    public int id;
    public String username;
    public String password;
    public String name;
    public boolean autherror=false;
    public String error="";
    public String signup = "Sign up";
    
    public int authenticate()
    {
        char ch=(mod==1)?'F':'S';
        String querry = "select * from authentication where username LIKE \'"+username+"\' and password LIKE \'"+password+"\' and who like \'"+ch+"\';";
        //System.out.println(querry);
       try{  
        Class.forName(ms.driver);  
        try (Connection con = DriverManager.getConnection(  
            ms.url,ms.username,ms.password)) {
   
            Statement stmt=con.createStatement();
            ResultSet rs=stmt.executeQuery(querry);
            rs.next();
           //System.out.println(rs.getString(1));
           if ("".equals(rs.getString(1)))
           {
            autherror=true;
            return -1;
        }   
        return (Integer.parseInt(rs.getString(1)));
        }
}catch(Exception e){ 
    //System.out.println(e);
}  
        return 0;
}
   public Loginn(int i,String err) {
        mod = i;
        error = err;
        
        if (i == 1)
            name = "Faculty Portal";
         else if (i == 0)
            name = "Students Portal";
        else
        {
            name = "Admin Portal";
            signup = "";
        }
       
        
        initComponents();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelUsername = new javax.swing.JLabel();
        textfusername = new javax.swing.JTextField();
        labelpassword = new javax.swing.JLabel();
        textfpassword = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        ButtonLogin = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(name);

        labelUsername.setBackground(java.awt.Color.lightGray);
        labelUsername.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelUsername.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelUsername.setText("Username");

        textfusername.setPreferredSize(null);
        textfusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfusernameActionPerformed(evt);
            }
        });

        labelpassword.setBackground(java.awt.Color.white);
        labelpassword.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelpassword.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelpassword.setText("Password");

        textfpassword.setPreferredSize(null);
        textfpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfpasswordActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText(error);

        ButtonLogin.setBackground(java.awt.Color.white);
        ButtonLogin.setText("Login");
        ButtonLogin.setPreferredSize(null);
        ButtonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonLoginActionPerformed(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText(signup);
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(0, 0, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Forgot Password");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        jMenu1.setText("Back");
        jMenu1.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenu1MenuSelected(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(436, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(labelUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(textfusername, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(labelpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(textfpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(ButtonLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(46, 46, 46))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(192, Short.MAX_VALUE)
                .addComponent(labelUsername)
                .addGap(5, 5, 5)
                .addComponent(textfusername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(labelpassword)
                .addGap(5, 5, 5)
                .addComponent(textfpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel1)
                .addGap(6, 6, 6)
                .addComponent(ButtonLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jLabel3)
                .addGap(6, 6, 6)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(108, 108, 108))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textfusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfusernameActionPerformed

    private void textfpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfpasswordActionPerformed

    private void ButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonLoginActionPerformed
        // TODO add your handling code here:
        username = textfusername.getText();
        password = textfpassword.getText();
        if ("".equals(username) || "".equals(password))
        return;
        if(mod == -1 && username.equals("admin") && password.equals("admin"))
        {
            dispose();
            new AdminProfile("",1).show();
            return;
        }

        int tid = authenticate();
        //System.out.println(tid);
        if(tid>0)
        {

            dispose();
            if (mod==1)
            new FUProfile(tid).setVisible(true);
            else
            new StProfile(tid).setVisible(true);

        }
        else
        {
            dispose();
            new Loginn(mod,"Enter valid username and password").show();

        }

    }//GEN-LAST:event_ButtonLoginActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        // TODO add your handling code here:
        dispose();
        if (mod==1)
        new SignUpF(" ").show();
        else
        new SignUpSt(" ").show();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        dispose();
        new ForgotPassword('F',"").show();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jMenu1MenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenu1MenuSelected
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jMenu1MenuSelected


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel labelUsername;
    private javax.swing.JLabel labelpassword;
    private javax.swing.JPasswordField textfpassword;
    private javax.swing.JTextField textfusername;
    // End of variables declaration//GEN-END:variables
}
