
package test.db;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

public class FUProfile extends javax.swing.JFrame {

    MySQLConnect ms = new MySQLConnect();
    public int id;
    public int courseid;
    public String name;
    public String username;
    public String password;
    public String branch;
    public String clgname;
    public String course;
    public String clgaddr;
    
    public FUProfile(int i) {
        id = i;
        
        try{  
        Class.forName(ms.driver);  
        
            try (Connection con = DriverManager.getConnection(  
                    ms.url,ms.username,ms.password)) {
                String querry = "SELECT f.id,f.name,a.username,a.password,f.branch,c.name,clg.name,clg.adress,c.id FROM faculty f,course c,college clg,authentication a where f.clgid = clg.clgid and f.courseid = c.id and a.id = f.id and f.id = "+id+";";
                Statement stmt=con.createStatement();
                //System.out.println(querry);
                ResultSet rs=stmt.executeQuery(querry);
                rs.next();
                name = rs.getString(2);
                username = rs.getString(3);
                password = rs.getString(4);
                branch  = rs.getString(5);
                course = rs.getString(6);
                clgname = rs.getString(7);
                clgaddr = rs.getString(8);  
                courseid = Integer.parseInt(rs.getString(9));
        }    
        }  catch(SQLException e){ System.out.println(e);} catch (ClassNotFoundException ex) {  
            Logger.getLogger(FUProfile.class.getName()).log(Level.SEVERE, null, ex);
        }  
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenu2 = new javax.swing.JMenu();
        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        logout = new javax.swing.JButton();
        updatemark = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfname = new javax.swing.JTextField();
        tfbranch = new javax.swing.JTextField();
        tfclg = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        addressCLG = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        tfname1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        tfclg1 = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        Home = new javax.swing.JMenu();

        jMenu1.setText("jMenu1");

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jMenu2.setText("jMenu2");

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Profile - Faculty");
        setName(""); // NOI18N
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logout.setText("Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        updatemark.setText("Update Marklist");
        updatemark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatemarkActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test/db/pf.png"))); // NOI18N

        jButton1.setText("Change Password");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(updatemark, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(updatemark)
                .addGap(15, 15, 15)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(logout)
                .addGap(30, 30, 30))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 314));

        jLabel1.setText("Name");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 40, 79, 23));

        jLabel2.setText("Branch");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 69, 79, 23));

        jLabel5.setText("Course");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 103, 79, 23));

        jLabel6.setText("College Address");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 164, 79, 23));

        tfname.setEditable(false);
        tfname.setText(name
        );
        tfname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfnameActionPerformed(evt);
            }
        });
        getContentPane().add(tfname, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 41, 205, -1));

        tfbranch.setEditable(false);
        tfbranch.setText(branch);
        tfbranch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfbranchActionPerformed(evt);
            }
        });
        getContentPane().add(tfbranch, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 70, 205, -1));

        tfclg.setEditable(false);
        tfclg.setText(course);
        getContentPane().add(tfclg, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 104, 205, -1));

        addressCLG.setEditable(false);
        addressCLG.setColumns(20);
        addressCLG.setRows(5);
        addressCLG.setText(clgaddr);
        jScrollPane1.setViewportView(addressCLG);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 164, 205, -1));

        jLabel9.setText("ID");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 11, 79, 23));

        tfname1.setEditable(false);
        tfname1.setText(Integer.toString(id));
        getContentPane().add(tfname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 12, 205, -1));

        jLabel10.setText("College");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 132, 79, 23));

        tfclg1.setEditable(false);
        tfclg1.setText(clgname);
        getContentPane().add(tfclg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 133, 205, -1));

        Home.setText("Home");
        jMenuBar1.add(Home);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfbranchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfbranchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfbranchActionPerformed

    private void tfnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfnameActionPerformed

    private void updatemarkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatemarkActionPerformed
        // TODO add your handling code here:
        new FUMarklist(id,name,courseid,course,branch,"").setVisible(true);
    }//GEN-LAST:event_updatemarkActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_logoutActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new ChangePassword('F',"").show();
    }//GEN-LAST:event_jButton1ActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Home;
    private javax.swing.JTextArea addressCLG;
    private javax.swing.JButton jButton1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton logout;
    private javax.swing.JTextField tfbranch;
    private javax.swing.JTextField tfclg;
    private javax.swing.JTextField tfclg1;
    private javax.swing.JTextField tfname;
    private javax.swing.JTextField tfname1;
    private javax.swing.JButton updatemark;
    // End of variables declaration//GEN-END:variables
}
